/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juanlopez_lab6p2;

import java.awt.HeadlessException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jjlm1
 */
public class Boroaa extends javax.swing.JFrame {

    /**
     * Creates new form Boroaa
     */
    public Boroaa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_equipo = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_pais = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_ciudad = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        bt_agregar = new javax.swing.JButton();
        jd_jugador = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jb_posicion = new javax.swing.JComboBox<>();
        bt_jugador = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jd_transferencia = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_mercado = new javax.swing.JTree();
        bt_florentino = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pp_jugador = new javax.swing.JPopupMenu();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        pp_elim = new javax.swing.JPopupMenu();
        jmi_elimi = new javax.swing.JMenuItem();
        pp_transferencia = new javax.swing.JPopupMenu();
        jmi_eli = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btl_equ = new javax.swing.JButton();
        btl_juga = new javax.swing.JButton();
        btl_trans = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_equ = new javax.swing.JMenuItem();
        jmi_juga = new javax.swing.JMenuItem();
        jmi_trans = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel6.setText("Crear Equipos");

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel7.setText("País del Equipo");

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel8.setText("Nombre del Equipo");

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel9.setText("Ciudad del Equipo");

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel10.setText("Estadio");

        tf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ciudadActionPerformed(evt);
            }
        });

        tf_estadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_estadioActionPerformed(evt);
            }
        });

        bt_agregar.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 18)); // NOI18N
        bt_agregar.setForeground(new java.awt.Color(0, 0, 51));
        bt_agregar.setText("Crear equipo");
        bt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_equipoLayout = new javax.swing.GroupLayout(jd_equipo.getContentPane());
        jd_equipo.getContentPane().setLayout(jd_equipoLayout);
        jd_equipoLayout.setHorizontalGroup(
            jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_agregar)
                    .addGroup(jd_equipoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tf_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(jd_equipoLayout.createSequentialGroup()
                        .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_pais, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(tf_nombre)))
                    .addGroup(jd_equipoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(78, 78, 78)
                        .addComponent(tf_estadio))
                    .addComponent(jLabel6))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_equipoLayout.setVerticalGroup(
            jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_equipoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_jugador.setBackground(new java.awt.Color(102, 102, 0));
        jd_jugador.setFocusTraversalPolicyProvider(true);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Crear Jugadores");

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Posición");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        jb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero", "Aguatero" }));

        bt_jugador.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 18)); // NOI18N
        bt_jugador.setText("Crear jugador");
        bt_jugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_jugadorMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/Captura de pantalla 2024-02-23 185504.png"))); // NOI18N

        javax.swing.GroupLayout jd_jugadorLayout = new javax.swing.GroupLayout(jd_jugador.getContentPane());
        jd_jugador.getContentPane().setLayout(jd_jugadorLayout);
        jd_jugadorLayout.setHorizontalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(bt_jugador))
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jd_jugadorLayout.createSequentialGroup()
                                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_name)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_jugadorLayout.setVerticalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_jugador)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadorLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jd_transferencia.setBackground(new java.awt.Color(255, 255, 153));
        jd_transferencia.setForeground(new java.awt.Color(255, 0, 204));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel11.setText("Transferencias");

        jl_jugadores.setModel(new DefaultListModel());
        jl_jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_jugadores);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("**Equipos**");
        jt_mercado.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_mercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_mercadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_mercado);

        bt_florentino.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 24)); // NOI18N
        bt_florentino.setForeground(new java.awt.Color(255, 0, 0));
        bt_florentino.setText("Here we go");
        bt_florentino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bt_florentino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_florentinoMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/OIP.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|°|");

        javax.swing.GroupLayout jd_transferenciaLayout = new javax.swing.GroupLayout(jd_transferencia.getContentPane());
        jd_transferencia.getContentPane().setLayout(jd_transferenciaLayout);
        jd_transferenciaLayout.setHorizontalGroup(
            jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transferenciaLayout.createSequentialGroup()
                .addGroup(jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_transferenciaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(bt_florentino, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_transferenciaLayout.setVerticalGroup(
            jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transferenciaLayout.createSequentialGroup()
                .addGroup(jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_florentino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_transferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmi_modificar.setText("Modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        pp_jugador.add(jmi_modificar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        pp_jugador.add(jmi_eliminar);

        jmi_elimi.setText("jMenuItem1");
        jmi_elimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_elimiActionPerformed(evt);
            }
        });
        pp_elim.add(jmi_elimi);

        jmi_eli.setText("Eliminar equipo");
        jmi_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliActionPerformed(evt);
            }
        });
        pp_transferencia.add(jmi_eli);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOROA LEAGUE FANTASY");

        jToolBar1.setBackground(new java.awt.Color(0, 102, 102));
        jToolBar1.setRollover(true);

        btl_equ.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btl_equ.setText("Crear Equipo");
        btl_equ.setFocusable(false);
        btl_equ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btl_equ.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btl_equ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btl_equMouseClicked(evt);
            }
        });
        jToolBar1.add(btl_equ);

        btl_juga.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btl_juga.setText("Crear Jugadores");
        btl_juga.setFocusable(false);
        btl_juga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btl_juga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btl_juga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btl_jugaMouseClicked(evt);
            }
        });
        jToolBar1.add(btl_juga);

        btl_trans.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btl_trans.setText("Transferencias");
        btl_trans.setFocusable(false);
        btl_trans.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btl_trans.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btl_trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btl_transMouseClicked(evt);
            }
        });
        jToolBar1.add(btl_trans);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/Captura de pantalla 2024-02-23 190718.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 204));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu1.setText("Opciones");

        jmi_equ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_equ.setText("Crear Equipo");
        jmi_equ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_equActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_equ);

        jmi_juga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_juga.setText("Crear Jugador");
        jmi_juga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_jugaActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_juga);

        jmi_trans.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_trans.setText("Transferencia");
        jmi_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_transActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_trans);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_transActionPerformed
        // TODO add your handling code here:
        jd_transferencia.pack(); 
        jd_transferencia.setLocationRelativeTo(this);
        jd_transferencia.setModal(true);
        jd_transferencia.setVisible(true);
    }//GEN-LAST:event_jmi_transActionPerformed

    private void jmi_jugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_jugaActionPerformed
        // TODO add your handling code here:
        jd_jugador.pack(); 
        jd_jugador.setLocationRelativeTo(this);
        jd_jugador.setModal(true);
        jd_jugador.setVisible(true);
    }//GEN-LAST:event_jmi_jugaActionPerformed

    private void jmi_equActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_equActionPerformed
        // TODO add your handling code here:
        jd_equipo.pack(); 
        jd_equipo.setLocationRelativeTo(this);
        jd_equipo.setModal(true);
        jd_equipo.setVisible(true);
    }//GEN-LAST:event_jmi_equActionPerformed

    private void tf_estadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_estadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_estadioActionPerformed

    private void tf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ciudadActionPerformed

    private void bt_jugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_jugadorMouseClicked
        // TODO add your handling code here:
        DefaultListModel m=(DefaultListModel) jl_jugadores.getModel();
        m.addElement(new Jugadores(tf_name.getText(), jb_posicion.getSelectedItem().toString(), (Integer)sp_edad.getValue()));
        jl_jugadores.setModel(m);
        tf_name.setText("");
        jb_posicion.setSelectedItem("Portero");
        sp_edad.setValue(15);
    }//GEN-LAST:event_bt_jugadorMouseClicked

    private void btl_equMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btl_equMouseClicked
        // TODO add your handling code here:
        jd_equipo.pack(); 
        jd_equipo.setLocationRelativeTo(this);
        jd_equipo.setModal(true);
        jd_equipo.setVisible(true);
    }//GEN-LAST:event_btl_equMouseClicked

    private void btl_jugaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btl_jugaMouseClicked
        // TODO add your handling code here:
        jd_jugador.pack(); 
        jd_jugador.setLocationRelativeTo(this);
        jd_jugador.setModal(true);
        jd_jugador.setVisible(true);
    }//GEN-LAST:event_btl_jugaMouseClicked

    private void btl_transMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btl_transMouseClicked
        // TODO add your handling code here:
        jd_transferencia.pack(); 
        jd_transferencia.setLocationRelativeTo(this);
        jd_transferencia.setModal(true);
        jd_transferencia.setVisible(true);
    }//GEN-LAST:event_btl_transMouseClicked

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed
        // TODO add your handling code here:
        try{
        String nuevo=JOptionPane.showInputDialog("Ingrese el nuevo nombre");
        int ed=Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva edad entre 15 y 45"));
            int centi=0;
        if (nuevo.contains("1")) {
                centi++;
            }else if (nuevo.contains("2")) {
                centi++;
            }else if (nuevo.contains("3")) {
                centi++;
            }else if (nuevo.contains("4")) {
                centi++;
            }else if (nuevo.contains("5")) {
                centi++;
            }else if (nuevo.contains("6")) {
                centi++;
            }else if (nuevo.contains("7")) {
                centi++;
            }else if (nuevo.contains("8")) {
                centi++;
            }else if (nuevo.contains("9")) {
                centi++;
            }else if (nuevo.contains("0")) {
                centi++;
            }
            if (centi==0&&ed>=15&&ed<=45) {
                DefaultListModel s=(DefaultListModel)jl_jugadores.getModel();
                ((Jugadores) s.get(control)).setNombre(nuevo);
                ((Jugadores) s.get(control)).setEdad(ed);
            }else{
                JOptionPane.showMessageDialog(jd_transferencia, "Error en la modificación");
            }
        }catch (HeadlessException | NumberFormatException ex){
            JOptionPane.showMessageDialog(jd_transferencia, "Error en la nueva edad");
        }
        
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jl_jugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadoresMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if(jl_jugadores.getSelectedIndex()>=0){
                control=jl_jugadores.getSelectedIndex();
                pp_jugador.show(jd_transferencia, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_jugadoresMouseClicked

    private void bt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarMouseClicked
        // TODO add your handling code here:
        Equipos t =new Equipos(tf_nombre.getText(), tf_pais.getText(), tf_ciudad.getText(), tf_estadio.getText());
        DefaultTreeModel m=(DefaultTreeModel)jt_mercado.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode pais=new DefaultMutableTreeNode(t.getPais());
        DefaultMutableTreeNode nom=new DefaultMutableTreeNode(t);
        int ocu=0;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(t.getPais())) {
                ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(nom);
                ocu++;
            }
        }
        if(ocu==0){
        pais.add(nom);
        raiz.add(pais);
        m.reload();
        }else{
            
        }
        tf_nombre.setText("");
        tf_ciudad.setText("");
        tf_estadio.setText("");
        tf_pais.setText("");
        
        
    }//GEN-LAST:event_bt_agregarMouseClicked

    private void bt_florentinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_florentinoMouseClicked
        // TODO add your handling code here:
        control=jl_jugadores.getSelectedIndex();
        try{
        if(jl_jugadores.getSelectedIndex()>=0){
            Equipos p;
            Jugadores c;
            DefaultListModel ss=(DefaultListModel)jl_jugadores.getModel();
            DefaultTreeModel tt=(DefaultTreeModel)jt_mercado.getModel();
            c=((Jugadores)ss.get(control));
            String nomb=c.getNombre();
            DefaultMutableTreeNode nombree=new DefaultMutableTreeNode(nomb);
            DefaultMutableTreeNode posi=new DefaultMutableTreeNode(c.getPosicion());
            Object trans=jt_mercado.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode compa=(DefaultMutableTreeNode)trans;
            if (compa.getUserObject()instanceof Equipos) {
                int cont=0;
                for (int i = 0; i < compa.getChildCount(); i++) {
                    if (compa.getChildAt(i).toString().equals(c.getPosicion())) {
                        ((DefaultMutableTreeNode)compa.getChildAt(i)).add(nombree);
                        cont++;
                    }
                }
                if (cont==0) {
                    compa.add(posi);
                    posi.add(nombree);
                }
                tt.reload();
            }
                
        }
        }catch(Exception ex){
        }
    }//GEN-LAST:event_bt_florentinoMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel q=(DefaultListModel)jl_jugadores.getModel();
        String nombre=((Jugadores)q.getElementAt(control)).getNombre();
        q.remove(control);
        jl_jugadores.setModel(q);
        DefaultTreeModel rr=(DefaultTreeModel)jt_mercado.getModel();
        DefaultMutableTreeNode r=(DefaultMutableTreeNode)rr.getRoot();
        for (int i = 0; i < r.getChildCount(); i++) {
            DefaultMutableTreeNode pp=((DefaultMutableTreeNode)r.getChildAt(i));
            for (int j = 0; j < pp.getChildCount(); j++) {
                DefaultMutableTreeNode ee=((DefaultMutableTreeNode)pp.getChildAt(j));
                for (int k = 0; k < ee.getChildCount(); k++) {
                    DefaultMutableTreeNode po=((DefaultMutableTreeNode)ee.getChildAt(k));
                    for (int l = 0; l < po.getChildCount(); l++) {
                        DefaultMutableTreeNode jj=((DefaultMutableTreeNode)po.getChildAt(l));
                        if (jj.toString().equals(nombre)){
                        rr.removeNodeFromParent(jj);
                        }
                    }
                }
            }
        }
        rr.reload();
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_elimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_elimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_elimiActionPerformed

    private void jt_mercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_mercadoMouseClicked
        // TODO add your handling code here:
        try{
        if (evt.isMetaDown()) {
            Object com=jt_mercado.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode del=(DefaultMutableTreeNode)com;
            if (del.getUserObject()instanceof Equipos) {
                pp_transferencia.show(jd_transferencia, evt.getX(), evt.getY());
            }
        }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jt_mercadoMouseClicked

    private void jmi_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel mm=(DefaultTreeModel)jt_mercado.getModel();
        Object com=jt_mercado.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode del=(DefaultMutableTreeNode)com;
            del.removeFromParent();
            mm.reload();
            
    }//GEN-LAST:event_jmi_eliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boroaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boroaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boroaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boroaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boroaa().setVisible(true);
            }
        });
    }
int control=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_florentino;
    private javax.swing.JButton bt_jugador;
    private javax.swing.JButton btl_equ;
    private javax.swing.JButton btl_juga;
    private javax.swing.JButton btl_trans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> jb_posicion;
    private javax.swing.JDialog jd_equipo;
    private javax.swing.JDialog jd_jugador;
    private javax.swing.JDialog jd_transferencia;
    private javax.swing.JList<String> jl_jugadores;
    private javax.swing.JMenuItem jmi_eli;
    private javax.swing.JMenuItem jmi_elimi;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_equ;
    private javax.swing.JMenuItem jmi_juga;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_trans;
    private javax.swing.JTree jt_mercado;
    private javax.swing.JPopupMenu pp_elim;
    private javax.swing.JPopupMenu pp_jugador;
    private javax.swing.JPopupMenu pp_transferencia;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pais;
    // End of variables declaration//GEN-END:variables
}
